### ISSUE TITLE
ld error

### ISSUE THREAD

**Issue by zjshf** [prouast/heartbeat#1]
## Thanks your code ,but when i compile the source code , the error happend
undefined reference to symbol 'avcodec_open2@@LIBAVCODEC_FFMPEG_56'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libavcodec.so: error adding symbols: DSO missing from command line

**Comment by prouast** [comment]
I haven't tested this code on Linux, can't reproduce the problem. It looks like a linker issue with ffmpeg. Check your local installation (especially libavcodec) and make sure that the .so can be found according to linker flag.
