### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by ErfanDL** [prouast/heartbeat#10]
Hi thanks for sharing this project. when I compile and running the heartbeat file showing the below error:
```
Using algorithm 0.
Face classifier xml not found!
```

any way to fix ?

thanks

**Comment by prouast** [comment]
Make sure the file haarcascade_frontalface_alt.xml is located in the same directory as the compiled code.

**Comment by ErfanDL** [comment]
thanks for reply. does it working on ubuntu with opencv 3.2 ? or only working on the 3.1 ? because when I compile and running program not opened and showing the below code:
```

root@Anonymous:~/heartbeat# ./Heartbeat 
Using algorithm 0.
rPPG online
Processing live feed
SIZE: 640x480
FPS: 30
TIME BASE: 0.001
START ALGORITHM
Not valid, finding a new face
Scanning for faces…
Found a face
Update mask
```
thanks

**Comment by prouast** [comment]
@ErfanDL I can't test this because I don't have a Ubuntu machine here. The output you shared looks like it is working. Is the only problem that the GUI isn't appearing?

**Comment by cploveflower** [comment]
hello,prouast!I put the haarcascade_frontalface_alt.xml is located in the same directory as the compiled code on the windows,but it still show the Face classifier xml not found!I don't why?can you tell me please

**Comment by cploveflower** [comment]
> @prouast thanks for reply. the problem is solved with Ubuntu 18.04 and OpenCV 3.4.1. now the program working perfectly

I also have the same problem ，I want to know how to deal with it by you?thank you!

**Comment by prouast** [comment]
> hello,prouast!I put the haarcascade_frontalface_alt.xml is located in the same directory as the compiled code on the windows,but it still show the Face classifier xml not found!I don't why?can you tell me please

Please make sure that the file is named in the same way as indicated in the [code](https://github.com/prouast/heartbeat/blob/24e6555dba40c4c8b34cb951ef8de4bf0fe24589/Heartbeat.cpp#L26), and in the same directory as the compiled program - then it should work. You could also try using the dnn face detector using the option `-facedet dnn`.

**Comment by cploveflower** [comment]
Thank  you for the answer,and I want to know the reason why the video of the moveing mask and the Image  all have the bpm?
