### ISSUE TITLE
Compile Error: fatal error: opencv2/core/core.hpp: No such file or directory  #include <opencv2/core/core.hpp>

### ISSUE THREAD

**Issue by DancingCryptos** [prouast/heartbeat#11]
Hi!
When I try to compile, I get bunch of issues related to opencv2. such as:

 fatal error: opencv2/core/core.hpp: No such file or directory
 #include <opencv2/core/core.hpp>

Any thoughts?

**Comment by prouast** [comment]
It sounds like opencv2 is missing. What OS are you working with? Have you installed opencv2? The headers need to be available on the compiler's standard search path when using the compile command from README.

**Comment by DancingCryptos** [comment]
Thank you! No, haven't installed opencv2. I didn't see that in the dependencies. Could you tell me where I can find opencv2? Is that a standard library like opencv?

**Comment by prouast** [comment]
The latest version if opencv will do (I think that is opencv 3.4) - it comes with the opencv2 dependencies you are missing. How to install will depend on the OS you are using.
