### ISSUE TITLE
Getting heart rate from one single picture

### ISSUE THREAD

**Issue by MLQUE** [prouast/heartbeat#13]
Hi

I took a video from one single picture for 20 seconds,then using it to test.however,I can also get the heart rate just like human's. Do you have any idea about this?

Regards
MLQUE

**Comment by prouast** [comment]
I am not quite sure what you are trying to do. Could you be more specific?

Thanks
Philipp

**Comment by MLQUE** [comment]
I used the tool to detect the heat beat from: 
(1) a video captured from a real, dynamic face
(2) a video captured from a face image, which is static and should have no heart beat.
We found the HR similar between the two.

![static](https://user-images.githubusercontent.com/30205035/48686090-28462280-ebf5-11e8-8a21-b108298b2ec3.jpg)
![dynamic](https://user-images.githubusercontent.com/30205035/48686092-28deb900-ebf5-11e8-93eb-67c9996a3ca0.jpg)

**Comment by prouast** [comment]
If you apply the algorithm on a static image, it will pick up random artifacts resulting in some value for bpm which has no meaning. When used correctly, it works best if there is a single steady light source, and not much subject movement.

**Comment by MLQUE** [comment]
Thank you!

**Comment by Edwardmark** [comment]
@prouast so could you please tell me how to eliminate the wrong heart beat in single image video? Thx.

**Comment by prouast** [comment]
You could mark the signal as too noisy if the signal does not seem to have a single dominating frequency component, i.e, the the highest peak in the frequency domain is relatively small in comparison to other frequencies.
