### ISSUE TITLE
id returned 1 exit status

### ISSUE THREAD

**Issue by Hasannajeeb** [prouast/heartbeat#15]
![image](https://user-images.githubusercontent.com/29169588/49145835-845e2480-f322-11e8-9187-19b8ec67bca8.png)

I cant figure out the problem. I am using windows 8, opencv 3.4.1, mingw32 minimalist compiler.

**Comment by prouast** [comment]
Try dropping the ffmpeg dependency (-lavcodec), they are not needed in the current version

**Comment by Hasannajeeb** [comment]
I solved this issue , it was because the libraries were not compatible for mingw. I downloaded mingw build opencv and this problem got solved.
