### ISSUE TITLE
Error on run, Face classifier xml not found!

### ISSUE THREAD

**Issue by Shauneoo** [prouast/heartbeat#17]
- Environment
MacOS Mojave 10.14.2

- Compiling using:
`g++ -std=c++11 -I/usr/local/Cellar/opencv/4.0.1/include/opencv4 -lopencv_core -lopencv_dnn -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_objdetect -lopencv_video -lopencv_videoio Heartbeat.cpp opencv.cpp RPPG.cpp Baseline.cpp -o Heartbeat`

- Getting following warnings

```RPPG.cpp:315:25: warning: 'estimateRigidTransform' is deprecated [-Wdeprecated-declarations]
        Mat transform = estimateRigidTransform(corners_0v, corners_1v, false);
                        ^
/usr/local/Cellar/opencv/4.0.1/include/opencv4/opencv2/video/tracking.hpp:258:1: note: 'estimateRigidTransform' has been explicitly marked deprecated here
CV_DEPRECATED CV_EXPORTS Mat estimateRigidTransform( InputArray src, InputArray dst, bool fullAffine );
^
/usr/local/Cellar/opencv/4.0.1/include/opencv4/opencv2/core/cvdef.h:346:43: note: expanded from macro 'CV_DEPRECATED'
#    define CV_DEPRECATED __attribute__ ((deprecated))
```

- Running Heartbeat getting following error
```
Using rPPG algorithm 0.
Using face detection algorithm 0.
Face classifier xml not found!

[Process completed]
```

- Even though 'haarcascade_frontalface_alt.xml' file is located in the same directory. Any guidance is appreciated.

**Comment by prouast** [comment]
I just tried and can't reproduce this on MacOS Mojave 10.14.3. Getting the same warnings during compilation due to deprecated method, but that's an unrelated issue.

The xml file is expected where you specified: https://github.com/prouast/heartbeat/blob/master/Heartbeat.cpp#L26

Try re-cloning or using DNN classifier using argument `-facedet deep`.

**Comment by Shauneoo** [comment]
Hi, tried recloning and running the following:
`g++ -std=c++11 -I/usr/local/Cellar/opencv/4.0.1/include/opencv4 -lopencv_core -lopencv_dnn -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_objdetect -lopencv_video -lopencv_videoio Heartbeat.cpp opencv.cpp RPPG.cpp Baseline.cpp -o -facedet deep Heartbeat`

Resulting in:
`clang: error: no such file or directory: 'deep'`

I've also checked the the xml is correctly located, I might be missing something obvious here.

**Comment by prouast** [comment]
I might have caused some confusion here, the argument `-facedet deep` should be used as an argument when running, not when compiling.

**Comment by Shauneoo** [comment]
Disregard, appears it was an issue with my OS. Reinstalled and functioning now. Cheers
