### ISSUE TITLE
Compile code for Windows

### ISSUE THREAD

**Issue by noob8** [prouast/heartbeat#2]
g++ -std=c++11 -LC:\Users\Anon\Desktop\ffmpeg-20171225-613f789-win32-shared\bin -LC:\Anaconda\pkgs\opencv3-3.1.0-py35_0\Library\lib -lopencv_core310 -lopencv_highgui310 -lopencv_imgcodecs310 -lopencv_imgproc310 -lopencv_objdetect310 -lopencv_video310 -lopencv_videoio310 -lavcodec-58 -lavformat-58 -lavutil-56 -lswscale-5 ?

**Comment by noob8** [comment]
Do you know how to fix WinMain@16 error in windows? 
: In function `main':/usr/src/debug/cygwin-2.9.0-3/winsup/cygwin/lib/libcmain.c:37: undefined reference to `WinMain@16'collect2: error: ld returned 1 exit status

**Comment by prouast** [comment]
Sorry, I haven't tried to compile this on Windows, only Unix. Also no Windows machine around to reproduce…

**Comment by noob8** [comment]
dont worry ive got it down to this so far:
g++ -std=c++11
-LC:\Users\Anon\Desktop\ffmpeg-20171225-613f789-win32-shared\bin
-LC:\Anaconda\pkgs\opencv3-3.1.0-py35_0\Library\lib
-LC:\MinGW\var\lib\mingw-get\data
-IC:\Anaconda\envs\mywindowscv\Library\include -lopencv_core310
-lopencv_highgui310 -lopencv_imgcodecs310 -lopencv_imgproc310
-lopencv_objdetect310 -lopencv_video310 -lopencv_videoio310 -lavcodec-58
-lavformat-58 -lavutil-56 -lswscale-5 -lmingw32-libarchive -lSDLMain
-mwindows Heartbeat.cpp FFmpegDecoder.cpp FFmpegEncoder.cpp opencv.cpp
RPPG.cpp Baseline.cpp -o Heartbeat
will setup ffmpeg to work then see if i still get winmain16 error

**Comment by noob8** [comment]
Got the developers version of FFMpeg and added -IC:\Users\Anon\Desktop\ffmpeg-20171225-613f789-win32-shared\include to g++

**Comment by prouast** [comment]
Did you manage to compile it for Windows?

**Comment by noob8** [comment]
no, i couldnt get it to work. i kept getting ffmpeg deprecated errors so
now i am working in ubuntu trying to compile. Still getting the same ffmpeg
deprecated error though. i read that ubuntu doesnt use ffmpeg but some
libavcodec or some such thing? i am new to the area still learning

**Comment by prouast** [comment]
That's too bad, sorry I can't be of more help. Anyways, libavcodec is part of ffmpeg. You can compile ffmpeg for Ubuntu: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

**Comment by iluvrachel** [comment]
I try to complie it on Windows 10 but failed.
there're several error show up even in openCV head file.
such like 
**Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'channels': is not a member of 'cv::DataType<_Tp>'	Heartbeat	d:\opencv\opencv\build\include\opencv2\core\mat.inl.hpp	1095**	

so weird
any idea?

**Comment by prouast** [comment]
I worked on the DataType issue. Please check if compilation error persists.

**Comment by coryhh** [comment]
Hi,
I have a question when I run the code. Hope that you could help me to get out.
The opencv version I am using is 3.4.1. I successfully compiled this code on windows 10. when I executed it,the code stays in the face detection function. The function is haarClassifier.detectMultiScale(frameGray, boxes, 1.1, 2, CV_HAAR_SCALE_IMAGE, minFaceSize);

Here is the result of  my execution：

Using rPPG algorithm 0.
Using face detection algorithm 0.
rPPG online
Processing live feed
SIZE: 640x480
FPS: 0
TIME BASE: 0.001
START ALGORITHM
Not valid, finding a new face
Scanning for faces...

**Comment by cploveflower** [comment]
> Thank you for your sharing. The problem has been solved.

can you tell me the way to compile it on windows 10?Thank you !

**Comment by coryhh** [comment]
> > 感谢您的分享。问题已经解决了。
> 
> 你能告诉我在Windows 10上编译它的方法吗？谢谢！

Can you describe your problem specifically?The software I use is VS 2015.The opencv version I am using is 3.4.1.

**Comment by Hasannajeeb** [comment]
> > > Thank you for your sharing. The problem has been solved.
> > 
> > 
> > can you tell me the way to compile it on windows 10?Thank you !
> 
> Can you describe your problem specifically?The software I use is VS 2015.The opencv version I am using is 3.4.1.

can you please tell me how did you compile it on windows using vs2015? i am using mingw32 to compile and getting this error, "Id returned 1 exit status"

**Comment by cploveflower** [comment]
> > > Thank you for your sharing. The problem has been solved.
> > 
> > 
> > can you tell me the way to compile it on windows 10?Thank you !
> 
> Can you describe your problem specifically?The software I use is VS 2015.The opencv version I am using is 3.4.1.
i use VS2013 and opencv3.1.0,can you tell me the command to compile it on the windows conmand ?thank you

**Comment by Hasannajeeb** [comment]
![image](https://user-images.githubusercontent.com/29169588/49284014-2e6db600-f4b5-11e8-8b65-361738b30e5e.png)
I somehow managed to compile the code through mingw. Now This is what i am getting after executing the exe file. I have updated .net framework and visual c++ but still cant get rid of it. Is there something missing in the project code?

**Comment by coryhh** [comment]
> ![image](https://user-images.githubusercontent.com/29169588/49284014-2e6db600-f4b5-11e8-8b65-361738b30e5e.png)
> I somehow managed to compile the code through mingw. Now This is what i am getting after executing the exe file. I have updated .net framework and visual c++ but still cant get rid of it. Is there something missing in the project code?

The DNN face recognition module in OpenCV is in opencv_contrib, you should use cmake to compile them to get the dnn module. You need to add the new header and library files generated after compilation to the command.

**Comment by coryhh** [comment]
> > > > Thank you for your sharing. The problem has been solved.
> > > 
> > > 
> > > can you tell me the way to compile it on windows 10?Thank you !
> > 
> > 
> > Can you describe your problem specifically?The software I use is VS 2015.The opencv version I am using is 3.4.1.
> > i use VS2013 and opencv3.1.0,can you tell me the command to compile it on the windows conmand ?thank you

Sorry, I have not used them to compile this code. I don't know what your problem is. Can you provide a specific description like pictures, errors, etc.

**Comment by cploveflower** [comment]
> Thank you for your sharing. The problem has been solved.

I want to know how to deal with it by you?I also have the same problem,and the picture's size is different with you ,it's 1280*720,and the result show :
Using rPPG algorithm 0.
Using face detection algorithm 0.
rPPG online
Processing live feed
SIZE: 1280*720
FPS: 30.02
TIME BASE: 0.001
START ALGORITHM
Not valid, finding a new face
Scanning for faces... 
found no face
it repeat the results all the time.can you help me please?

**Comment by prouast** [comment]
> > Thank you for your sharing. The problem has been solved.
> 
> I want to know how to deal with it by you?I also have the same problem,and the picture's size is different with you ,it's 1280_720,and the result show : Using rPPG algorithm 0. Using face detection algorithm 0. rPPG offline Processing live feed SIZE: 1280_720
> FPS: 30.02
> TIME BASE: 0.001
> START ALGORITHM
> Not valid, finding a new face
> Scanning for faces...
> found no face
> it repeat the results all the time.can you help me please?

This means that the face detector did not find your face. Try to move closer to the camera, remove hair and glasses from face, etc.

**Comment by Hasannajeeb** [comment]
> > ![image](https://user-images.githubusercontent.com/29169588/49284014-2e6db600-f4b5-11e8-8b65-361738b30e5e.png)
> > I somehow managed to compile the code through mingw. Now This is what i am getting after executing the exe file. I have updated .net framework and visual c++ but still cant get rid of it. Is there something missing in the project code?
> 
> The DNN face recognition module in OpenCV is in opencv_contrib, you should use cmake to compile them to get the dnn module. You need to add the new header and library files generated after compilation to the command. The version of opencv_contrib must be the same as the version of opencv. The compiler should use c++14.



how

> > ![image](https://user-images.githubusercontent.com/29169588/49284014-2e6db600-f4b5-11e8-8b65-361738b30e5e.png)
> > I somehow managed to compile the code through mingw. Now This is what i am getting after executing the exe file. I have updated .net framework and visual c++ but still cant get rid of it. Is there something missing in the project code?
> 
> The DNN face recognition module in OpenCV is in opencv_contrib, you should use cmake to compile them to get the dnn module. You need to add the new header and library files generated after compilation to the command. The version of opencv_contrib must be the same as the version of opencv. The compiler should use c++14.

can you share the exact command used to make it run please?
