### ISSUE TITLE
How to run on windows10

### ISSUE THREAD

**Issue by jujuran2** [prouast/heartbeat#21]
How to run on windows10？

**Comment by LEESEONGHWAM** [comment]
I used WSL(window subsystem linux) Ubuntu 18.04 LTS version.
This method required OpenCV 3.4.0 (upper) version, Xming (something like a Ubuntu GUI performing server program). 
Try it :)

**Comment by nalinmittal** [comment]
*Download OpenCV 4.0.1 for windows.
*Install it in Visual Studio 17 for C++.
*Build and Run.
*Remove warnings from the compiler settings.

**Comment by prouast** [comment]
Thanks @nalinmittal  for the steps, I'll close this.

**Comment by wang-yu1016** [comment]
> *下载适用于Windows的OpenCV 4.0.1。
> *将其安装在Visual Studio 17 for C ++中。
> *构建并运行。
> *从编译器设置中删除警告。



> *Download OpenCV 4.0.1 for windows.
> *Install it in Visual Studio 17 for C++.
> *Build and Run.
> *Remove warnings from the compiler settings.

could pl

**Comment by wang-yu1016** [comment]
could you please tell me how to Build and Run？
