### ISSUE TITLE
Increasing performance and tweaking

### ISSUE THREAD

**Issue by nalinmittal** [prouast/heartbeat#22]
First of all, thank you for the amazing research done @prouast. I was wondering whether the FPS affects the accuracy of the pulse count. I am getting ~6.5 FPS on my PC. I saw on your youtube video that you were getting constant 30FPS. Also my FPS count was variable and not locked. If there is a way to lock FPS let me know.

**Comment by prouast** [comment]
Thanks @nalinmittal. It is true that a higher FPS allows the pulse estimate to be more accurate. The way to get a constant FPS is to pre-record a video, and then feed it into the algorithm using the `-i` argument (pulse estimation is then not live).

**Comment by nalinmittal** [comment]
That's helpful to know! But are there any other ways to run 30 FPS on live estimation.

Also how to performance boost because if I pre-record a 30 FPS video it does not seem to run realtime fast.

**Comment by prouast** [comment]
To boost performance, you would either want a faster system or someone would need to optimize the code. Although it is written in C++, I did not pay very much attention to that, so I am sure it could be improved.
