### ISSUE TITLE
Does it work on Windows 10? 

### ISSUE THREAD

**Issue by tyhu97** [prouast/heartbeat#23]
I have found no effective steps to build and run.

**Comment by tyhu97** [comment]
I tried it on Ubuntu 18.04 and opecv 3.4.1. Output is :
Using rPPG alorithm 0
Using face detection algorithm 0

That's all. How can I fix it?

**Comment by tyhu97** [comment]
It works perfect now. I think it's beacuse I run it on VirtualMachine before.

**Comment by wang-yu1016** [comment]
Does it work on Windows 10?
