### ISSUE TITLE
OSC output

### ISSUE THREAD

**Issue by stephanschulz** [prouast/heartbeat#27]
Thank you so much for sharing this create example project.
It works very well as far as I can tell.

You know what would be super nice ;), if your code would integrate OSC (open sound control) as an output option. This would make it so easy for other to grab that data and use it in their own projects. Also it would make it Independent of c++.

Just a thought.

All the best.

**Comment by prouast** [comment]
Thanks for your interest in this project. You can always feel free to send a pull request to add functionality.
