### ISSUE TITLE
Environment requirements

### ISSUE THREAD

**Issue by zxh009123** [prouast/heartbeat#3]
Hi,
I can compile and run the Heartbeat demo now. But I see the bpm value is varying all the time. I think the reason cause this issue is the difference between my test environment and your develop environment. Can you provide the environment requirements for this project (like inside or outside, how much light should project on face etc.).

thank you

**Comment by prouast** [comment]
It generally works best indoors with a static artificial light source, and when there is not a lot of movement. You can also try to adjust the parameters. For example, using the pca algorithm and with a max time window of 12 sec: `./Heartbeat -a pca -max 12`

**Comment by zxh009123** [comment]
That's helpful!
Thanks.
