### ISSUE TITLE
Confusion on rescanning

### ISSUE THREAD

**Issue by connormeaton** [prouast/heartbeat#32]
Hello. I am trying to understand the rescanning portion of your code here:

https://github.com/prouast/heartbeat/blob/0d671adf5d5a01a054c7fcf0c223aa65c7ecf686/RPPG.cpp#L101

How is this condition satisfied and what is its purpose? I am assuming `time` is incremented by 1, so how is `time-lastScanTime' never != 1? Also, it looks like timeBase is set to .001, so how can `(time - lastScanTime) * timeBase` ever be >= 1/reScanFrequency? From my understanding, this results in .001 >= 1, which is never true. Please let me know what I am missing.

Thanks!

**Comment by prouast** [comment]
`(time - lastScanTime) * timeBase` computes the time since we last used the face detector. Your assumption about `time` is wrong. It is passed as an argument to this function and is denominated in milliseconds. Hope this helps your understanding of the code 👍
