### ISSUE TITLE
Measure high bpm after workout. 

### ISSUE THREAD

**Issue by vkehfdl1** [prouast/heartbeat#38]
Hello. At first, thank you for your amazing work!
I tried to get high heartrate using your code, but I can't achieve it. When I measure heartrate at 30 fps, I could detect high bpm easily , but below 15 fps I couldn't detect high bpm. 
I tried to figure out why, so I analyzed raw signal and figured out there is so much fluctuation after workout. Maybe this is the reason why I can't get high bpm at low fps. 
However, I watched your youtube video about rppg, and I shocked because you can get high bpm at low fps. 
So, I wonder why this happens and how can I get high bpm at low fps. Please let me know. 

Thank you for your great work again!

**Comment by prouast** [comment]
This may have to do with the moving average filtering window size parameter. With a high frame rate and low sampling rate, peaks may be too close together.

**Comment by vkehfdl1** [comment]
Thanks for your reply. I solved this issue with higher framerate, zero-padding, and other method choosing ROIs. 
And delete moving Average filter and modify HIGH_BPM parameter to 200. It helps me get narrow bandpass filter. Moving average filter didn't effect much in my experiments. 
Thank you for your advice and codes.
