### ISSUE TITLE
Code performance and porting to Python

### ISSUE THREAD

**Issue by DiTo97** [prouast/heartbeat#41]
Hi @prouast,

First all of all, thanks for the great work. I wanted to ask two things specifically:

1. Is this code base still relevant with respect to the current SOTA in rPPG estimation? If not, which are the improvements that you think should be tackled with the highest priority at its current state?
2. How robust to motion is your implementation?
3. How challenging would it be to port it all to Python? I gave a quick glance at the repository, and was debating which path would be the easiest between re-implementing your whole logic in Python or wrapping your C++ code with Python binders.

As you may have already assumed, I would need this code to talk to a larger Python module.

**Comment by prouast** [comment]
Hi, is a finished project from 2016 containing a very naive implementation of rPPG. If you would like to build a SOTA model in Python, I would recommend starting from scratch.
