### ISSUE TITLE
Poor performance with video files recorded using auto settings on DSLR camera

### ISSUE THREAD

**Issue by matt-sharp** [prouast/heartbeat#42]
I have recorded some video footage using a Nikon D750 DSLR camera and have kept auto-focus and auto for all other settings.  The room is well lit, the subjects face fills the frame and there is little movement.
The results are poor when compared to the ground-truth, which has been measured using a Polar H10 chest-strap sensor.
When checking the metadata for the videos I have noticed that the ISO varies significantly (280 - 1800) across different subjects.  In particular, it's high for those with dark skin tone and performs poorly with those.  The best performing subject doesn't have the lowest ISO though.

@prouast Is the ISO a significant factor in determining the quality of the results or is there anything else I should consider with the data?

**Comment by prouast** [comment]
Hi Matt, the rPPG method implemented in this repository is one of the simplest possible. It is intended as a simple demo that can be run in real-time. If you are looking for higher accuracy, you may want to check out implementations of more recent approaches.

The worse performance especially for darker skin tones is also a known issue (e.g., https://openaccess.thecvf.com/content_CVPRW_2020/papers/w19/Nowara_A_Meta-Analysis_of_the_Impact_of_Skin_Tone_and_Gender_CVPRW_2020_paper.pdf)
