### ISSUE TITLE
Is there a respiratory rate implementation 

### ISSUE THREAD

**Issue by MoatazNoaman2001** [prouast/heartbeat#43]
Hi, iam working on rppg for about 4 months and I take this project as a source to study from I changed some stuff like using ncnn implantation and more my question is there is respiratory rate implantation to use in cpp   

edit: i read a lot on hypered can and mtts can but this need lots of efforts to be generated for android device any advice?

**Comment by prouast** [comment]
Hi @MoatazNoaman2001, the scope of this repository is only pulse estimation with naive green channel and PCA methods. The project is not actively developed anymore but you are free to fork and work on it.
