### ISSUE TITLE
update Repo

### ISSUE THREAD

**Issue by MoatazNoaman2001** [prouast/heartbeat#44]
could you update the repo to include pos ,fav and chrome algorithms

**Comment by prouast** [comment]
Hi @MoatazNoaman2001, the scope of this repository is only pulse estimation with naive green channel and PCA methods. The project is not actively developed anymore but you are free to fork and work on it.

**Comment by MoatazNoaman2001** [comment]
> Hi @MoatazNoaman2001, the scope of this repository is only pulse estimation with naive green channel and PCA methods. The project is not actively developed anymore but you are free to fork and work on it.

Thank you for your response. I will do my best on it
