### ISSUE TITLE
OpenCV Error

### ISSUE THREAD

**Issue by javadziaratnia** [prouast/heartbeat#5]
Hi 
After compiling the source-code, and trying to run the program I got this error.
Do you have nay idea for fixing this issue?

centan@centan-Vostro-3800:~/Desktop/Heartbeat$ ./Heartbeat
Using algorithm 0.
SIZE: 640x480
FPS: 30
MSEC: 0
Tracking face
OpenCV Error: Assertion failed ((npoints = prevPtsMat.checkVector(2, CV_32F, true)) >= 0) in calcOpticalFlowPyrLK, file /home/centan/Downloads/opencv-3.1.0/modules/video/src/lkpyramid.cpp, line 1114
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/centan/Downloads/opencv-3.1.0/modules/video/src/lkpyramid.cpp:1114: error: (-215) (npoints = prevPtsMat.checkVector(2, CV_32F, true)) >= 0 in function calcOpticalFlowPyrLK

**Comment by prouast** [comment]
Thanks for the feedback. Haven't had time to look into this project for a while. I will try my best to get to the bottom of this in the next few weeks.

**Comment by prouast** [comment]
Please check if error persists.

**Comment by javadziaratnia** [comment]
Hi
Thanks for your reply.
Unfortunately, still I'm getting this error.

Using algorithm 0.
SIZE: 640x480
FPS: 30
MSEC: 0
Tracking face
OpenCV Error: Assertion failed ((npoints = prevPtsMat.checkVector(2, CV_32F, true)) >= 0) in calcOpticalFlowPyrLK, file /home/centan/Downloads/opencv-3.1.0/modules/video/src/lkpyramid.cpp, line 1114
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/centan/Downloads/opencv-3.1.0/modules/video/src/lkpyramid.cpp:1114: error: (-215) (npoints = prevPtsMat.checkVector(2, CV_32F, true)) >= 0 in function calcOpticalFlowPyrLK

Aborted (core dumped)

**Comment by prouast** [comment]
I can't reproduce this issue, however I am using opencv 3.4.1. Maybe updating opencv could help. What OS and run settings were used?

**Comment by javadziaratnia** [comment]
Thank you very much it fixed

**Comment by iglaweb** [comment]
@javadziaratnia how did you fix this issue? I'm experiencing the same error
