### ISSUE TITLE
Heart rate changes rapidly

### ISSUE THREAD

**Issue by javadziaratnia** [prouast/heartbeat#6]
Hi
Actually heart rate changes rapidly for example from 80 to 50 then 70 ... .
So i think the max change should be for instance 2 BPM per second. Do you have any idea about this?

My second question is about the time in csv file. Could you please explain a little bit about it? (eg. 9394881, 9395903, 9396906)

Also could please explain a little bit about max time window ?

And finally, because i think your app is not accurate when there are a lot of movements and also the system could not detect face at a distance more than 0.5 m. Do you think using dlib will improve your app?

Regards
Javad

**Comment by prouast** [comment]
This is only a simple reference implementation of rPPG. For more accuracy/more consistent HR estimates, try to have a consistent indoor light source, and as little as possible subject movement.

You are free to experiment with the minimum required relative face size: https://github.com/prouast/heartbeat/blob/master/RPPG.cpp#L23

For any of the other questions, please send me an email, thanks!

**Comment by connormeaton** [comment]
@prouast I've had a similar problem. How does experimenting with minimum required relative face size improve rapid changes in BPM? If I understand correctly, REL_MIN_FACE_SIZE sets the minimum face size requirement in the haar cascade classifier to be 40% (default) of the frame size. Is this the correct understanding and if so, how does this help the problem? I've experimented with values from .01 to .99 and see no real difference. Thanks.
